### ISSUE TITLE
ReferenceError: Class is not defined

### ISSUE THREAD

**Issue by rohit-saharan** [dominiek/node-facebook#4]
Followed the instructions, but when i do node app.js, this is the error I get:

ReferenceError: Class is not defined
    at Object.<anonymous> (/var/www/myproject/lib/facebook.js:7:21)
    at Module._compile (node.js:462:23)
    at Module._loadScriptSync (node.js:469:10)
    at Module.loadSync (node.js:338:12)
    at loadModule (node.js:283:14)
    at require (node.js:411:14)
    at Object.<anonymous> (/var/www/myproject/app.js:6:1)
    at Module._compile (node.js:462:23)
    at Module._loadScriptSync (node.js:469:10)
    at Module.loadSync (node.js:338:12)

Regards

**Comment by francois2metz** [comment]
Hi,

take a look on https://github.com/francois2metz/node-facebook/
